name: Fetch table

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 12 * * *"

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Download HTML
        run: |
          mkdir -p data
          curl https://www.gwinnettcounty.com/content/departments/elections/WaitTimes/WaitTimes.html --output data/$(date +%Y%m%d_%H%M%S).html
      - name: Push changes
        run: |
          git config user.email "kerryrodden@users.noreply.github.com"
          git config user.name "Gwinnett County wait times (bot)"
          git add -A
          git commit -m "Adding data from $(date +%Y-%m-%d, %H:%M:%S)"
          git push origin main
